import assert from "node:assert/strict";
import test from "node:test";
import { createMockServer } from "../../mock/server.mjs";
import ManageBacPlus from "../dist/index.js";

test("generated SDK calls every endpoint against the mock server", async () => {
  const server = createMockServer();
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  const port = typeof address === "object" && address ? address.port : 0;
  try {
    let observed = 0;
    const client = new ManageBacPlus({ apiKey: "test", baseUrl: `http://127.0.0.1:${port}`, validateResponses: true, hooks: { onResponse: () => { observed += 1; } } });
    await client.coursework.listGradesForClass({ "classId": 1, "termId": 1 });
    await client.coursework.listTermGradesForClass({ "classId": 1, "termId": 1 });
    await client.attendance.setAttendanceSettings({ "classId": 1, "academicYearId": 1, body: { "settings": [{ "period": 1, "day": 1 }] } });
    await client.attendance.listCategories("test");
    await client.authentication.listTokenResources();
    await client.authentication.createOauthToken({ body: { "grantType": "client_credentials", "clientId": "test", "clientSecret": "test" } });
    await client.utilities.showAvatarById("test");
    await client.utilities.ping();
    await client.behaviorNotes.listBehaviorNotes({  });
    await client.coursework.listCriteriaforClass("test");
    await client.memberships.getStudentsForClass({ "classId": 1 });
    await client.extendedApis.bulkUpdateStudentsFromClass({ "classId": 1, body: { "students": [{  }] } });
    await client.coursework.listClassTaskCategories("test");
    await client.coursework.downloadSubmissionFile({ "classId": 1, "taskId": 1, "studentId": 1, "assetId": 1 });
    await client.coursework.listTaskSubmissions({ "classId": 1, "taskId": 1 });
    await client.coursework.getTaskSubmission({ "classId": 1, "taskId": 1, "studentId": 1 });
    await client.coursework.listTasksforClass({ "id": 1 });
    await client.coursework.getTasksByIdforClass({ "id": 1, "classId": 1 });
    await client.coursework.updateTaskforClass({ "classId": 1, "id": 1, body: { "coreTask": { "authorId": 1, "name": "test", "dueDate": "test", "assessmentTypeId": 1 } } });
    await client.coursework.partialUpdateTaskforClass({ "classId": 1, "id": 1, body: { "coreTask": {  } } });
    await client.coursework.deleteTaskforClass({ "classId": 1, "id": 1 });
    await client.coursework.listStudentAssessmentResultsForClassTask({ "id": 1, "classId": 1 });
    await client.attendance.getClassTimetable({ "classId": 1 });
    await client.classes.listClasses({  });
    await client.classes.createClass({ body: {  } });
    await client.extendedApis.upsertClasses({ body: {  } });
    await client.classes.getClassById("test");
    await client.classes.updateClass({ "id": 1, body: {  } });
    await client.classes.addStudentsToClass({ "id": 1, body: { "studentIds": [1] } });
    await client.classes.removeStudentsFromClass({ "id": 1, body: { "studentIds": [1] } });
    await client.attendance.getAttendanceForClass({ "id": 1, "termId": 1 });
    await client.attendance.getClassAttendanceForDate({ "id": 1, "date": "test" });
    await client.extendedApis.setClassAttendanceForStudents({ "id": 1, body: { "attendances": [{  }] } });
    await client.classes.getClassTerms({ "id": 1 });
    await client.attendance.getDateExcusals({ "date": "test" });
    await client.attendance.getAttendanceForYearGroupByTerm({ "yearGroupId": 1, "termId": 1 });
    await client.attendance.getAttendanceForYearGroupByDate({ "yearGroupId": 1, "date": "test" });
    await client.attendance.getAttendanceAdjustmentsForYearGroupByTerm({ "yearGroupId": 1, "termId": 1 });
    await client.memberships.listMemberships({  });
    await client.relationships.listOfParentChildrenRelationships({ "parentId": "test" });
    await client.relationships.createParentChildRelationship({ "parentId": "test", body: { "child": {  } } });
    await client.relationships.bulkUpdateParentChildrenRelationships({ "parentId": "test", body: { "children": [{  }] } });
    await client.relationships.getParentChildRelationship({ "parentId": "test", "id": "test" });
    await client.relationships.updateParentChildRelationship({ "parentId": "test", "id": "test", body: { "child": {  } } });
    await client.relationships.deleteParentChildRelationship({ "parentId": "test", "id": "test" });
    await client.parents.listParents({  });
    await client.parents.createParent({ body: { "parent": {  } } });
    await client.parents.getParentById("test");
    await client.parents.updateParent({ "id": 1, body: { "parent": {  } } });
    await client.parents.archiveParent("test");
    await client.parents.unarchiveParent("test");
    await client.parents.sendParentWelcomeEmail("test");
    await client.academics.createAcademicTerm({ "programCode": "test", "academicYearId": "test", body: {  } });
    await client.academics.updateAcademicTerm({ "programCode": "test", "academicYearId": "test", "id": "test", body: {  } });
    await client.academics.deleteAcademicTerm({ "programCode": "test", "academicYearId": 1, "id": 1 });
    await client.academics.retrieve({ "programCode": "test", "id": 1 });
    await client.academics.createAcademicYear({ "programCode": "test", body: {  } });
    await client.academics.getAssessmentTypes("test");
    await client.academics.list({ "programCode": "test", "academicYearId": 1 });
    await client.academics.getAllTermReports({ "program": "test" });
    await client.academics.getTermReport({ "program": "test", "id": 1 });
    await client.academics.downloadTermReportFile({ "program": "test", "id": 1, "kind": "test" });
    await client.academics.getSubjectGroups({ "programCode": "test" });
    await client.academics.createSubjectGroup({ "programCode": "test", body: {  } });
    await client.academics.getSubjectGroup({ "programCode": "test", "id": 1 });
    await client.academics.updateSubjectGroup({ "programCode": "test", "id": 1, body: {  } });
    await client.academics.destroySubjectGroup({ "programCode": "test", "id": 1 });
    await client.academics.getSubjects({ "programCode": "test" });
    await client.academics.createSubject({ "programCode": "test", body: {  } });
    await client.academics.getSubject({ "programCode": "test", "id": 1 });
    await client.academics.updateSubject({ "programCode": "test", "id": 1, body: {  } });
    await client.academics.deleteSubject({ "programCode": "test", "id": 1 });
    await client.extendedApis.bulkEnableSubjects({ "programCode": "test", body: {  } });
    await client.extendedApis.bulkDisableSubjects({ "programCode": "test", body: {  } });
    await client.academics.getSchool();
    await client.academics.listAcademicYears({  });
    await client.academics.listGrades();
    await client.academics.listSubjects();
    await client.academics.listSchoolTermGradeScales();
    await client.academics.listTermRubrics();
    await client.students.updateStudentAvatar({ "id": 1, body: {  } });
    await client.students.deleteStudentAvatar("test");
    await client.attendance.getStudentExcusals({ "studentId": 1 });
    await client.attendance.createStudentExcusal({ "studentId": 1, body: {  } });
    await client.extendedApis.updateStudentExcusal({ "studentId": 1, "id": 1, body: {  } });
    await client.extendedApis.deleteStudentExcusal({ "studentId": 1, "id": 1 });
    await client.students.listStudents({  });
    await client.students.createStudent({ body: { "student": {  } } });
    await client.students.getStudentById("test");
    await client.students.updateStudent({ "id": 1, body: {  } });
    await client.students.archiveStudent({ "id": 1, body: {  } });
    await client.students.unarchiveStudent("test");
    await client.memberships.getStudentMemberships({ "id": 1 });
    await client.extendedApis.setStudentHomeroomAttendance({ "id": 1, body: {  } });
    await client.students.sendStudentWelcomeEmail("test");
    await client.onlineAssessment.updateOnlineAssessment({ "taskId": 1, "assessPrepUid": "test", body: {  } });
    await client.extendedApis.updateStudentTaskGrades({ "taskId": 1, "studentId": 1, body: {  } });
    await client.extendedApis.bulkUpdateStudentTaskGrades({ "taskId": 1, body: {  } });
    await client.coursework.bulkResetStudentsTaskGrades({ "taskId": 1, body: {  } });
    await client.teachers.updateTeacherAvatar({ "id": 1, body: {  } });
    await client.teachers.deleteTeacherAvatar("test");
    await client.teachers.listTeachers({  });
    await client.teachers.createTeacher({ body: { "teacher": {  } } });
    await client.teachers.getTeacherById("test");
    await client.teachers.updateTeacher({ "id": 1, body: { "teacher": {  } } });
    await client.teachers.archiveTeacher("test");
    await client.teachers.unarchiveTeacher("test");
    await client.teachers.listTeacherClassesMemberships({ "id": 1 });
    await client.teachers.listTeacherGroupsMemberships({ "id": 1 });
    await client.teachers.sendTeacherWelcomeEmail("test");
    await client.unitClassAssignments.listUnitClassAssignments({  });
    await client.units.listUnits({  });
    await client.units.getUnitById("test");
    await client.projects.listYearGroupCasExperiencesStudents({ "id": 1 });
    await client.projects.getYearGroupCas("test");
    await client.projects.listYearGroupPblProposalStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblReflectionsStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblTodosStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblJournalStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblDocumentsStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblPresentationStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupPblNotesAndInterviewsStudentsDetails({ "yearGroupId": 1, "projectId": 1 });
    await client.projects.listYearGroupProjectBasedLearningTemplates({ "id": 1 });
    await client.yearGroups.listYearGroupServiceLearningCategoriesStudents({ "id": 1 });
    await client.yearGroups.listYearGroupServiceLearningOutcomesStudents({ "id": 1 });
    await client.yearGroups.getYearGroupServiceLearning("test");
    await client.yearGroups.listYearGroups({  });
    await client.yearGroups.listStudentsFromYearGroups({ "id": 1 });
    await client.yearGroups.addStudentToYearGroup({ "id": 1, body: { "studentIds": [1] } });
    await client.yearGroups.removeStudentToYearGroup({ "id": 1, body: { "studentIds": [1] } });
    await client.yearGroups.listAdvisorsFromYearGroup("test");
    await client.memberships.getTeacherMemberships("test");
    await client.extendedApis.bulkUpdateTeacherMemberships({ "classId": 1, body: { "teachers": [{  }] } });
    await client.classes.addTeachersToClass({ "classId": 1, body: { "teacherIds": [1] } });
    await client.memberships.removeTeachersFromClass({ "classId": 1, body: { "teacherIds": [1] } });
    await client.coursework.createTaskforClass({ "classId": 1, body: { "coreTask": { "authorId": 1, "name": "test", "dueDate": "test", "assessmentTypeId": 1 } } });
    {
      const raw = await client.attendance.withRawResponse.listCategories("test");
      assert.equal(raw.response.status, 200, "raw response exposes status");
      assert.ok(raw.data !== undefined, "raw response exposes parsed data");
    }


    assert.ok(observed > 0, "observability hook fired");
  } finally {
    server.closeAllConnections?.();
    await new Promise((resolve) => server.close(resolve));
  }
});
